version: '3'

services:
  trading-system:  # 实盘交易应该用 trading-system
    build: .
    container_name: trading-system
    restart: always
    environment:
      - DOCKER_ENVIRONMENT=true
      - ALPACA_API_KEY=${ALPACA_LIVE_API_KEY}  # 使用实盘 API 密钥
      - ALPACA_API_SECRET=${ALPACA_LIVE_API_SECRET}  # 使用实盘 API 密钥
      - ALPACA_PAPER=false  # 设置为 false 表示实盘交易
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_QUANT_DB=${MYSQL_QUANT_DB}
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: trading-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_QUANT_DB}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data: