version: '3'

services:
  trading-system:
    build: .
    container_name: trading-system
    restart: always
    environment:
      - DOCKER_ENVIRONMENT=true
      - ALPACA_PAPER=false
      - ALPACA_PAPER_API_KEY=${ALPACA_PAPER_API_KEY}
      - ALPACA_PAPER_API_SECRET=${ALPACA_PAPER_API_SECRET}
      - ALPACA_LIVE_API_KEY=${ALPACA_LIVE_API_KEY}
      - ALPACA_LIVE_API_SECRET=${ALPACA_LIVE_API_SECRET}
      - ALPACA_LIVE_URL=${ALPACA_LIVE_URL}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_QUANT_DB=${MYSQL_QUANT_DB}
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: trading-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_QUANT_DB}
      - MYSQL_USER=quant_user      # Changed from root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uquant_user", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql-data: