version: '3'

services:
  trading-system:
    platform: linux/amd64  # 指定平台为x86以避免ARM兼容性问题
    build: .
    container_name: trading-system
    restart: always
    environment:
      - DOCKER_ENVIRONMENT=true
      - ALPACA_PAPER=false  # 设置为 false 表示实盘交易
      - ALPACA_PAPER_API_KEY=${ALPACA_PAPER_API_KEY}
      - ALPACA_PAPER_API_SECRET=${ALPACA_PAPER_API_SECRET}
      - ALPACA_LIVE_API_KEY=${ALPACA_LIVE_API_KEY}
      - ALPACA_LIVE_API_SECRET=${ALPACA_LIVE_API_SECRET}
      - ALPACA_LIVE_URL=${ALPACA_LIVE_URL}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_QUANT_DB=${MYSQL_QUANT_DB}
      - TZ=America/Los_Angeles
      - RISK_PERCENT=0.02
      - MAX_POSITIONS=5
      - STOP_LOSS_PERCENT=0.05
      - TRAILING_STOP_PERCENT=0.02
      - MAX_DRAWDOWN_LIMIT=-0.15
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      - mysql

  mysql:
    platform: linux/amd64  # 指定平台为x86以避免ARM兼容性问题
    image: mysql:8.0
    container_name: trading-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_QUANT_DB}
      - TZ=America/Los_Angeles
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data: